config/routes.rb
Rails.application.routes.draw do
  resources :website_links
  get 'agent_websites/import'
  get 'profile/show'
  get 'agent_websites/crawler'
  get 'agent_websites/settings'
  get 'agent_websites/trendings'



  root to: 'welcom#index'

  resources :dummies
  devise_for :agents
  resources :agent_websites
end

app/models/website_link.rb
# == Schema Information
#
# Table name: website_links
#
#  id         :integer          not null, primary key
#  website    :string(255)
#  link       :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class WebsiteLink < ApplicationRecord
end

app/controllers/website_links_controller.rb
class WebsiteLinksController < ApplicationController
  before_action :set_website_link, only: [:show, :edit, :update, :destroy]

  # GET /website_links
  # GET /website_links.json
  def index
    @website_links = WebsiteLink.all
  end

  # GET /website_links/1
  # GET /website_links/1.json
  def show
  end

  # GET /website_links/new
  def new
    @website_link = WebsiteLink.new
  end

  # GET /website_links/1/edit
  def edit
  end

  # POST /website_links
  # POST /website_links.json
  def create
    @website_link = WebsiteLink.new(website_link_params)

    respond_to do |format|
      if @website_link.save
        format.html { redirect_to @website_link, notice: 'Website link was successfully created.' }
        format.json { render :show, status: :created, location: @website_link }
      else
        format.html { render :new }
        format.json { render json: @website_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /website_links/1
  # PATCH/PUT /website_links/1.json
  def update
    respond_to do |format|
      if @website_link.update(website_link_params)
        format.html { redirect_to @website_link, notice: 'Website link was successfully updated.' }
        format.json { render :show, status: :ok, location: @website_link }
      else
        format.html { render :edit }
        format.json { render json: @website_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /website_links/1
  # DELETE /website_links/1.json
  def destroy
    @website_link.destroy
    respond_to do |format|
      format.html { redirect_to website_links_url, notice: 'Website link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website_link
      @website_link = WebsiteLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_link_params
      params.require(:website_link).permit(:website, :link)
    end
end

app/helpers/website_links_helper.rb
module WebsiteLinksHelper
end

app/views/website_links/_form.html.erb
<%= form_for(website_link) do |f| %>
  <% if website_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website_link.errors.count, "error") %> prohibited this website_link from being saved:</h2>

      <ul>
      <% website_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_area :link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/website_links/edit.html.erb
<h1>Editing Website Link</h1>

<%= render 'form', website_link: @website_link %>

<%= link_to 'Show', @website_link %> |
<%= link_to 'Back', website_links_path %>

app/views/website_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Website Links</h1>

<table>
  <thead>
    <tr>
      <th>Website</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @website_links.each do |website_link| %>
      <tr>
        <td><%= website_link.website %></td>
        <td><%= website_link.link %></td>
        <td><%= link_to 'Show', website_link %></td>
        <td><%= link_to 'Edit', edit_website_link_path(website_link) %></td>
        <td><%= link_to 'Destroy', website_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website Link', new_website_link_path %>

app/views/website_links/new.html.erb
<h1>New Website Link</h1>

<%= render 'form', website_link: @website_link %>

<%= link_to 'Back', website_links_path %>

app/views/website_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Website:</strong>
  <%= @website_link.website %>
</p>

<p>
  <strong>Link:</strong>
  <%= @website_link.link %>
</p>

<%= link_to 'Edit', edit_website_link_path(@website_link) %> |
<%= link_to 'Back', website_links_path %>